"""
This file is part of Hmark.

    Hmark is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    Hmark is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with Hmark.  If not, see <https://www.gnu.org/licenses/>.
"""

"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup
import os
import version
import platform

osName = "OSX"
version = version.version
cwd = os.getcwd()
APP = ['hmark.py']
APP_NAME = 'hmark_' + version + "_" + osName
DATA_FILES = ['icon.gif', 'ctags']
OPTIONS = {
    'argv_emulation': True,
    'iconfile': 'icon.gif',
    'plist': {
        'CFBundleName': APP_NAME,
        'CFBundleDisplayName': APP_NAME,
    }
}

setup(
    name=APP_NAME,
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
